name: distributed-task-queue

services:
  dev:
    image: maven:3.9.11-eclipse-temurin-21
    working_dir: /workspace 
    volumes:
      - .:/workspace:Z # SElinux - this specific container is allowed to read and write
      - maven-cache:/root/.m2 
    stdin_open: true # -i 
    tty: true # -t


  redis:
    image: redis:8.2.9-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 20
      start_period: 5s

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    command:
      - -host=0.0.0.0
      - -config=/config/toxiproxy.json
    volumes:
      - ./docker/toxiproxy.json:/config/toxiproxy.json:ro,Z
    ports:
      - "127.0.0.1:8474:8474"
      - "127.0.0.1:26379:26379"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/toxiproxy-cli", "list"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 5s

volumes:
  maven-cache:
  redis-data:
