name: distributed-task-queue

services:
  dev:
    image: maven:3.9.11-eclipse-temurin-21
    working_dir: /workspace 
    volumes:
      - .:/workspace:Z # SElinux - this specific container is allowed to read and write
      - maven-cache:/root/.m2 
    stdin_open: true # -i 
    tty: true # -t


  redis:
    image: redis:8.2.9-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 20
      start_period: 5s



volumes:
  maven-cache:
  redis-data:
